// ═══════════════════════════════════════════════════════════════
//  SHEIKH LAB — Publications Database
//
//  This file contains PI-authored papers where no current or
//  former lab member is a co-author.
//
//  Papers authored with lab members should be added to that
//  member's entry in people-data.js instead — they are merged
//  automatically at render time.
//
//  Deduplication: papers with matching title + journal across
//  both sources are counted only once.
//
//  type options:
//    "article"       → Journal Article
//    "review"        → Review Article
//    "book-chapter"  → Book Chapter
//    "conference"    → Conference Paper
//
//  featured: true → shows in Featured strip (max 3, latest first)
//  doi: ""        → hides the Copy DOI button
// ═══════════════════════════════════════════════════════════════
//  FORMAT
//
/*
    {
      title:    "Paper title placeholder",
      authors:  "Sheikh JA, Co-author B, Co-author C",
      journal:  "Journal Name",
      year:     2024,
      type:     "article",
      tags:     ["Tuberculosis", "Diagnostics"],
      doi:      "https://doi.org/10.xxxx/xxxxx",
      featured: true,
    },
*/
// ═══════════════════════════════════════════════════════════════

const PUBLICATIONS = {

  papers: [
    {
      title:    "The exploitation of host autophagy and ubiquitin machinery by Mycobacterium tuberculosis in shaping immune responses and host defense during infection",
      authors:  "Shariq M, Quadir N, Alam A, Zarin S, Sheikh JA, Sharma N, Samal J",
      journal:  "Autophagy",
      year:     2023,
      type:     "article",
      tags:     ["Tuberculosis", "Autophagy", "Immunology"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "COVID-19 and tuberculosis: the double whammy of respiratory pathogens",
      authors:  "Shariq M, Sheikh JA, Quadir N, Sharma N, Hasnain SE, Ehtesham NZ",
      journal:  "European Respiratory Review",
      year:     2022,
      type:     "review",
      tags:     ["COVID-19", "Tuberculosis", "Respiratory Diseases"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Emerging genetic diversity among clinical isolates of SARS-CoV-2: Lessons for today",
      authors:  "Sheikh JA, Singh J, Singh H, Jamal S, Khubaib M, Kohli S",
      journal:  "Infection, Genetics and Evolution",
      year:     2020,
      type:     "article",
      tags:     ["COVID-19", "Genomics", "SARS-CoV-2"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Mycobacterium tuberculosis Protein PE6 (Rv0335c), a Novel TLR4 Agonist, Evokes an Inflammatory Response and Modulates Cell Death Pathways",
      authors:  "Sharma N, Shariq M, Quadir N, Singh J, Sheikh JA, Hasnain SE",
      journal:  "Frontiers in Immunology",
      year:     2021,
      type:     "article",
      tags:     ["Tuberculosis", "TLR4", "Immunology"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Mycobacterium tuberculosis RipA Dampens TLR4-Mediated Host Protective Response via Autophagy and Apoptosis Modulation",
      authors:  "Shariq M, Quadir N, Sharma N, Singh J, Sheikh JA, Khubaib M",
      journal:  "Frontiers in Immunology",
      year:     2021,
      type:     "article",
      tags:     ["Tuberculosis", "Autophagy", "Cell Death"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Mycobacterium tuberculosis Co-operonic PE32/PPE65 Proteins Alter Host Immune Responses by Hampering Th1 Response",
      authors:  "Khubaib M, Sheikh JA, Pandey S, Srikanth B, Bhuwan M, Khan N",
      journal:  "Frontiers in Microbiology",
      year:     2016,
      type:     "article",
      tags:     ["Tuberculosis", "Immune Response", "Th1"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Mycobacterium tuberculosis Peptidyl-Prolyl Isomerases Are Immunogenic and Aid in Intracellular Survival",
      authors:  "Pandey S, Tripathi D, Khubaib M, Kumar A, Sheikh JA, Sumanlatha G",
      journal:  "Frontiers in Cellular and Infection Microbiology",
      year:     2017,
      type:     "article",
      tags:     ["Tuberculosis", "Proteins", "Pathogenesis"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Teleological cooption of Mycobacterium tuberculosis PE/PPE proteins as porins",
      authors:  "Ehtram A, Shariq M, Ali S, Quadir N, Sheikh JA, Ahmad F",
      journal:  "International Journal of Medical Microbiology",
      year:     2021,
      type:     "article",
      tags:     ["Tuberculosis", "Membrane Proteins", "Pathogenesis"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Can Mycobacterium tuberculosis infection lead to cancer? A paradigm shift",
      authors:  "Malik AA, Sheikh JA, Ehtesham NZ, Hira S, Hasnain SE",
      journal:  "International Journal of Medical Microbiology",
      year:     2022,
      type:     "review",
      tags:     ["Tuberculosis", "Cancer", "Pathogenesis"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Utility of B-cell epitopes based peptides for immunodiagnosis of pulmonary tuberculosis",
      authors:  "Goyal B, Kumar K, Gupta D, Agarwal R, Latawa R, Sheikh JA",
      journal:  "Diagnostic Microbiology and Infectious Disease",
      year:     2014,
      type:     "article",
      tags:     ["Tuberculosis", "Diagnostics", "Immunology"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Disorder-to-order transition in PE–PPE proteins augments pro-pathogen immune response",
      authors:  "Ahmad J, Khubaib M, Sheikh JA, Pancsa R, Kumar S",
      journal:  "FEBS Open Bio",
      year:     2020,
      type:     "article",
      tags:     ["Protein Structure", "Tuberculosis", "Immunity"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Regulation of autophagy by SARS-CoV-2: multifunctional contributions of ORF3a",
      authors:  "Shariq M, Malik AA, Sheikh JA, Hasnain SE, Ehtesham NZ",
      journal:  "Journal of Medical Virology",
      year:     2023,
      type:     "review",
      tags:     ["COVID-19", "Autophagy", "Virology"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Mycobacterium tuberculosis protein MoxR1 enhances virulence by disrupting host pathways",
      authors:  "Quadir N, Shariq M, Sheikh JA, Singh J, Sharma N",
      journal:  "Virulence",
      year:     2023,
      type:     "article",
      tags:     ["Tuberculosis", "Virulence", "Cell Death"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Learning from COVID-19 to tackle TB pandemic: from despair to hope",
      authors:  "Sheikh JA, Malik AA, Quadir N, Ehtesham NZ, Hasnain SE",
      journal:  "The Lancet Regional Health Southeast Asia",
      year:     2022,
      type:     "commentary",
      tags:     ["COVID-19", "Tuberculosis", "Public Health"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Mechanisms of immune evasion by Mycobacterium tuberculosis",
      authors:  "Malik AA, Shariq M, Sheikh JA, Jaiswal U, Fayaz H",
      journal:  "Critical Reviews in Biochemistry and Molecular Biology",
      year:     2024,
      type:     "review",
      tags:     ["Tuberculosis", "Immune Evasion", "Molecular Biology"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "The Molecular Arms Race: Xenophagy, Pathogen Evasion, and Host-Directed Therapies",
      authors:  "Ansari O, Ahmed F, Siddiquee N, Mursaleen A, Sheikh JA",
      journal:  "Microbiological Research",
      year:     2026,
      type:     "review",
      tags:     ["Autophagy", "Host-Pathogen Interaction", "Therapeutics"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Expression of a unique M. tuberculosis DNA methyltransferase Rv1509 in M. smegmatis alters gene expression and enhances virulence",
      authors:  "Manjunath P, Ahmad J, Samal J, Rani A, Sheikh JA, Zarin S, Ahuja Y",
      journal:  "Frontiers in Microbiology",
      year:     2024,
      type:     "article",
      tags:     ["Tuberculosis", "Epigenetics", "Virulence"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Revitalizing antimicrobial strategies: paromomycin and dicoumarol as inhibitors of Mycobacterium tuberculosis replication protein DnaN",
      authors:  "Ali W, Agarwal M, Jamal S, Gangwar R, Sharma R, Mubarak MM, Sheikh JA",
      journal:  "International Journal of Biological Macromolecules",
      year:     2024,
      type:     "article",
      tags:     ["Tuberculosis", "Drug Repurposing", "DNA Replication"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Phagosomal escape and sabotage: Role of ESX-1 and PDIMs in Mycobacterium tuberculosis pathogenesis",
      authors:  "Shariq M, Ahmed F, Ansari O, Mursaleen A, Sheikh JA",
      journal:  "International Reviews of Immunology",
      year:     2025,
      type:     "review",
      tags:     ["Tuberculosis", "ESX-1", "Immune Evasion"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Targeting DNA primase DnaG of Mycobacterium tuberculosis identifies mitoxantrone and vapreotide as growth inhibitors",
      authors:  "Ali W, Jamal S, Gangwar R, Ahmed F, Agarwal M, Sheikh JA",
      journal:  "Molecular Informatics",
      year:     2024,
      type:     "article",
      tags:     ["Tuberculosis", "Drug Discovery", "Enzymes"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Structure-based drug repurposing to inhibit replication protein DnaG of Mycobacterium tuberculosis",
      authors:  "Ali W, Jamal S, Gangwar R, Ahmed F, Agarwal M, Sheikh JA",
      journal:  "Drug Discovery Research Reports",
      year:     2023,
      type:     "article",
      tags:     ["Tuberculosis", "Drug Repurposing", "Bioinformatics"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Mycobacterium tuberculosis lysosomal damage response and selective autophagy: coordinated immune mechanisms",
      authors:  "Shariq M, Malik AA, Alam A, Sheikh JA, Hasnain SE",
      journal:  "FEMS Microbiology Reviews",
      year:     2025,
      type:     "review",
      tags:     ["Tuberculosis", "Autophagy", "Innate Immunity"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Immunodominant protein MIP_05962 of Mycobacterium indicus pranii exhibits chaperone activity and immune modulation",
      authors:  "Sharma A, Equbal MJ, Pandey S, Sheikh JA, Ehtesham NZ",
      journal:  "The FEBS Journal",
      year:     2017,
      type:     "article",
      tags:     ["Immunology", "Chaperone Proteins", "Mycobacteria"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Autophagy in Mycobacterium tuberculosis defense: complexities and mechanistic contradictions",
      authors:  "Shariq M, Alam A, Sheikh JA, Ehtesham NZ, Hasnain SE",
      journal:  "Clinical Science",
      year:     2021,
      type:     "review",
      tags:     ["Tuberculosis", "Autophagy", "Host Defense"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "COVID-19 challenges and lessons for infectious disease preparedness",
      authors:  "Badar MS, Ali W, Ansari O, Malik AA, Sheikh JA, Mursaleen A",
      journal:  "Academic Press Infectious Disease Series",
      year:     2025,
      type:     "book chapter",
      tags:     ["COVID-19", "Public Health", "Pandemics"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Replication and pathogenesis of coronaviruses: molecular mechanisms and host interactions",
      authors:  "Badar MS, Ansari O, Mursaleen A, Malik AA, Sheikh JA, Nehal A",
      journal:  "Elsevier Infectious Disease Compendium",
      year:     2024,
      type:     "book chapter",
      tags:     ["COVID-19", "Virology", "Coronaviruses"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "The molecular arms race: xenophagy, pathogen evasion and host-directed therapies",
      authors:  "Ansari O, Ahmed F, Siddiquee N, Mursaleen A, Sheikh JA",
      journal:  "Microbiological Research",
      year:     2026,
      type:     "review",
      tags:     ["Tuberculosis", "Xenophagy", "Therapeutics"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Deciphering functional roles of PE18 and PPE26 proteins in Mycobacterium tuberculosis pathogenesis",
      authors:  "Ehtram A, Shariq M, Quadir N, Jamal S, Pichipalli M, Zarin S, Sheikh JA",
      journal:  "Frontiers in Immunology",
      year:     2025,
      type:     "article",
      tags:     ["Tuberculosis", "PE/PPE Proteins", "Immune Modulation"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Challenges posed by COVID-19: clinical and public health perspectives",
      authors:  "Badar MS, Ali W, Ansari O, Malik AA, Sheikh JA, Mursaleen A",
      journal:  "Infectious Disease Monographs",
      year:     2024,
      type:     "book chapter",
      tags:     ["COVID-19", "Public Health", "Epidemiology"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Mycobacterium indicus pranii protein MIP_05962 induces Th1 cell-mediated immune response in mice",
      authors:  "Sharma A, Saqib MS, Sheikh JA, Ehtesham NZ, Bhaskar S, Chaudhuri TK",
      journal:  "International Journal of Medical Microbiology",
      year:     2018,
      type:     "article",
      tags:     ["Immunology", "Th1 Response", "Mycobacteria"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Utility of B-cell epitope-based peptides of RD1 and RD2 antigens for tuberculosis diagnosis",
      authors:  "Goyal B, Kumar KK, Gupta DG, Agarwal R, Sheikh JA",
      journal:  "Journal of Immunodiagnostics",
      year:     2014,
      type:     "article",
      tags:     ["Tuberculosis", "Diagnostics", "B-cell Epitope"],
      doi:      "https://example.com/publication",
      featured: false,
    },
    {
      title:    "Immunotherapeutic role of Ag85B as adjunct to antituberculous chemotherapy",
      authors:  "Sheikh JA, Khuller GK, Verma I",
      journal:  "Journal of Immune-Based Therapies and Vaccines",
      year:     2011,
      type:     "article",
      tags:     ["Tuberculosis", "Immunotherapy", "Vaccines"],
      doi:      "https://example.com/publication",
      featured: true,
    },
    {
      title:    "Sarcoid–tuberculosis link: evidence from a high TB prevalence setting",
      authors:  "Mootha VK, Agarwal R, Aggarwal AN, Gupta D, Ahmed J, Verma I",
      journal:  "Journal of Infection",
      year:     2010,
      type:     "article",
      tags:     ["Tuberculosis", "Sarcoidosis", "Differential Diagnosis"],
      doi:      "https://example.com/publication",
      featured: false,
    }
  ],

};